### ISSUE TITLE
fix: Need to update to latest version of Google provider

### ISSUE THREAD

**Issue by mikelaramie** [lacework/terraform-gcp-gar#5]
Google provider 4.0.0 has been released, but we are pinned to `~>3.0`

**Comment by afiune** [comment]
@mikelaramie Do you think we should prioritize this upgrade? Are users needing this upgrade? 

Normally, major version bumps mean a lot of work, we need to scope this before starting to work on it.

**Comment by afiune** [comment]
https://lacework.atlassian.net/browse/ALLY-768

**Comment by afiune** [comment]
Closed by https://github.com/lacework/terraform-gcp-gar/pull/13
